### ISSUE TITLE
SyntaxError pythongdb-gaudy/gdbaudy/bt.py, line 170

### ISSUE THREAD

**Issue by jhgorse** [asutherland/pythongdb-gaudy#1]
Perhaps due to python3 in gdb

```

$ gdb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jhg/Downloads/pythongdb-gaudy/gdbaudy/bt.py", line 170
    except RuntimeError, text:
                       ^
SyntaxError: invalid syntax
/home/jhg/.gdbinit:10: Error in sourced command file:
Error while executing Python code.
```

**Comment by asutherland** [comment]
Very probably!  I fear I haven't been using gdb and python too much as of late... there may be some other runtime issues that exist too.  But I'd be very happy to accept pull requests, etc.!
